GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

POST http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 277
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

g2_return=/gallery/main.php?&g2_formUrl=/gallery/main.php?g2_view=core.UserAdmin&g2_subView=core.UserLogin&g2_authToken=865cb4d33783&g2_controller=core.UserLogin&g2_form[formName]=UserLogin&g2_form[action][login]=Login&g2_form%5Busername%5D=admin&g2_form%5Bpassword%5D=password
GET http://bellog.org/gallery/main.php?g2_GALLERYSID=dbebc8283ef0bae34e2f21e6a02c253a HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/LJ8DHRpQ.htm HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/ysio5tsJ.jsp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/qUORM0tj.htmls HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/GXXXB03T.asp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/hLN8NIyF.cgi HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/kpY35LRy.do HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/Dw68q1op.gif HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/3ebcYo1D.rb HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/MzIxc4R5.py HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/cGSdHvjS.foobar HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/xqNBNnYO.pl HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/AA7utoMe.aspx HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/4RKj9VCW.xhtml HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/ocNc4RjB.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php?g2_view=core.ItemDeleteJs&g2_lang=en_US HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php?g2_return=%2Fgallery%2Fmain.php&g2_form%5BformName%5D=search_SearchBlock&g2_form%5BuseDefaultSettings%5D=1&g2_formUrl=%2Fgallery%2Fmain.php&g2_view=search.SearchScan&g2_form%5BsearchCriteria%5D=Search%20the%20Gallery&g2_authToken=b8d99460899b HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php?g2_view=core.ItemDeleteJs&g2_lang=en_US HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php?g2_view=core.CombinedJavascript&g2_key=c129ce38a587579eb8a5fdbf0bde4fb5 HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

