GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/vxdR3hY0.do HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/j7RD8LP8.foobar HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/HTFzdgKq.htm HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/X63TPRO2.xhtml HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/2k330Kiv.cgi HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/gZkGp9pM.htmls HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/4SYIjD16.pl HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/FHgZfaVF.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/jgTK5Lhb.gif HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/GgbDtDDE.asp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/WP5vv7PB.aspx HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/nIykPG2J.rb HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/GeXBOs7D.jsp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/AMEPEDEI.py HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

GET http://bellog.org/gallery/main.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

