GET http://bellog.org/oscommerce/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/1boXWr6h.jsp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/XslG3HSW.htm HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/ksviQRij.gif HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/6J5safov.cgi HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/cHNH1iAs.foobar HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/JVFXv7BA.asp HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/NXtPT5iZ.rb HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/gV83MLxk.xhtml HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/jWBmWfwy.do HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/1Z9DiugT.aspx HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/GS7ofFnH.py HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/lVN7wJ0C.htmls HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/YfPkYUp7.pl HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/HbWF03MV.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/speed.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/theres_something_about_mary.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/microsoft/intkeyboardps2.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/replacement_killers.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/octncat_su.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/microsoft/msimpro.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/the_matrix.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/stars_5.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/rpdocut_niof.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/pseed.gif HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/under_siege.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/matrox/mg200mms.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/store_logo.png HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/ HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/beloved.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/oscommerce/images/dvd/die_hard_3.gif HTTP/1.1
Referer: http://bellog.org/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

GET http://bellog.org/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: bellog.org
Accept: */*

