GET http://127.0.0.1/oscommerce/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/products_new.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/conditions.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/advanced_search_result.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/login.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/specials.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/reviews.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/advanced_search.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/checkout_shipping.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/create_account.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/account.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/ HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/contact_us.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/privacy.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/shopping_cart.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/shipping.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/advanced_search_result.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/conditions.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/oscommerce/products_new.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

