GET http://127.0.0.1/wordpress/wp-admin/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/ HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/nav-menus.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/post.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/export.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/plugin-editor.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/tools.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/plugins.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/edit-comments.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/options-media.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/customize.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/options-reading.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/import.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/options-permalink.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/index.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/options-discussion.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/themes.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/user-new.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/edit.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/wordpress/wp-admin/media-new.php HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

