GET http://127.0.0.1/bamboo/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

POST http://127.0.0.1/bamboo/index.php/login HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 29
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

username=a%40a.com&password=s
GET http://127.0.0.1/bamboo/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/settings HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/help HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/accounts HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/donate HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/invoices/newinvoice_first HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/logout/confirm HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/utilities HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/invoices HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/reports HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/clients HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 96
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=TRUE&client_id=1200&newClient=
POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 98
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=TRUE&client_id=1200&newClient=56
GET http://127.0.0.1/bamboo/index.php/invoices/newinvoice HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 170
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=r9fr3%3C%2F-%3Er9fr3%2F%2Ar9fr3%22r9fr3r9fr3%27r9fr3r9fr3%60r9fr3r9fr3%20%3D&client_id=1200&newClient=56
POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 105
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=zbhkr%2F%2A&client_id=1200&newClient=56
POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 107
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=92axa%2292axa&client_id=1200&newClient=56
