GET http://127.0.0.1/bamboo/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

POST http://127.0.0.1/bamboo/index.php/login HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 29
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

username=a%40a.com&password=s
GET http://127.0.0.1/bamboo/index.php HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/help HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/logout/confirm HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/accounts HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/donate HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/invoices/newinvoice_first HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

POST http://127.0.0.1/bamboo/index.php/clients/newclient HTTP/1.1
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 95
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

createInvoice=Create%20Invoice&newinvoicecancel=Cancel&newInvoice=TRUE&client_id=0&newClient=56
GET http://127.0.0.1/bamboo/index.php/utilities HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/invoices HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/settings HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/clients HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/help HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/clients/ HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/changelog HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/credits HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/donate HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Content-length: 0
Content-type: application/x-www-form-urlencoded
Host: 127.0.0.1
Accept: */*

GET http://127.0.0.1/bamboo/index.php/ HTTP/1.1
Referer: http://127.0.0.1/
Accept-encoding: gzip, deflate
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; w3af.org)
Host: 127.0.0.1
Accept: */*

